apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-creds
    namespace: ecommerce
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: |
        {"auths":{"https://index.docker.io/v1/":{"username":"Username","password":"Password/Token","auth":"VXNlcm5hbWU6UGFzc3dvcmQvVG9rZW4="}}}
