# MySQL credentials
# - password          → used by MySQL StatefulSet as root password
# - inventory-password / order-password → used by the application services
apiVersion: v1
kind: Secret
metadata:
    name: mysql-creds
    namespace: ecommerce
    labels:
        app.kubernetes.io/part-of: ecommerce
        app.kubernetes.io/component: database
type: Opaque
stringData:
    password: "mysqldb123"
    inventory-password: "InvAppSecur3Passw0rd!"
    order-password: "OrdAppSecur3Passw0rd!"
