apiVersion: v1
kind: Service
metadata:
    name: notification-service
    namespace: ecommerce
    labels:
        app.kubernetes.io/name: notification-service
        app.kubernetes.io/part-of: ecommerce
        observability: enabled
spec:
    type: ClusterIP
    selector:
        app.kubernetes.io/name: notification-service
    ports:
        - name: http
          port: 8084
          targetPort: 8084
