apiVersion: v1
kind: ResourceQuota
metadata:
    name: ecommerce-quota
    namespace: ecommerce
spec:
    hard:
        requests.cpu: "20"
        requests.memory: 40Gi
        limits.cpu: "40"
        limits.memory: 80Gi
        persistentvolumeclaims: "20"
        pods: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
    name: ecommerce-limit-range
    namespace: ecommerce
spec:
    limits:
        - type: Container
          defaultRequest:
              cpu: 100m
              memory: 128Mi
          default:
              cpu: 500m
              memory: 512Mi
          max:
              cpu: "4"
              memory: 4Gi
          min:
              cpu: 25m
              memory: 32Mi
