apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
    name: mailpit-pdb
    namespace: ecommerce
spec:
    minAvailable: 1
    selector:
        matchLabels:
            app.kubernetes.io/name: mailpit
