apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-infrastructure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: ecommerce
  source:
    repoURL: https://github.com/noman-akram29/ecommerce-platform-gitops.git
    targetRevision: main
    path: environments/kubeadm/staging
    directory:
      include: "{data/**,messaging/**,networking/**}"
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
