apiVersion: v1
kind: ConfigMap
metadata:
    name: inventory-service-config
    namespace: ecommerce
data:
    SERVER_PORT: "8081"
    SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/inventory_db"
    SPRING_DATASOURCE_USERNAME: "inventory_app"
