apiVersion: v1
kind: Service
metadata:
    name: inventory-service
    namespace: ecommerce
    labels:
        app.kubernetes.io/name: inventory-service
        app.kubernetes.io/part-of: ecommerce
        observability: enabled

spec:
    type: ClusterIP
    selector:
        app.kubernetes.io/name: inventory-service
    ports:
        - name: http
          port: 8081
          targetPort: 8081
